#!/usr/bin/env python3
"""
Generate src/data/books.js and cover images from PDFs in src/assets/pdfs.

Requirements:
  pip install pymupdf

What it does:
  - Renders the first page of each PDF to a JPG in src/assets/covers
  - Creates src/data/books.js with import statements for each PDF and cover
  - Assigns titles from a provided Arabic list (if count matches/order of PDFs)

Usage:
  python scripts/generate_books.py

Customize the ARABIC_TITLES list below to match your desired titles.
"""
from __future__ import annotations
import os
import re
import sys
from pathlib import Path

try:
    import fitz  # PyMuPDF
except ImportError:
    print("Missing dependency: PyMuPDF. Install with: pip install pymupdf", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
PDF_DIR = ROOT / "src" / "assets" / "pdfs"
COVERS_DIR = ROOT / "src" / "assets" / "covers"
OUT_JS = ROOT / "src" / "data" / "books.js"

# Titles provided by the user; order will map to sorted PDFs if counts allow
ARABIC_TITLES = [
    "الآلة التي وُلِدت",
    "الآلة التي تُفكّر",
    "الآلة التي تُحاور",
    "الآلة التي تشعر",
    "الآلة التي تُقلّد",
    "الآلة التي تُبدِع",
    "الآلة التي تتعلّم",
    "الآلة التي تتفاعل",
    "الآلة التي تنتج",
]

def slugify(name: str) -> str:
    base = re.sub(r"\.[Pp][Dd][Ff]$", "", name)
    base = re.sub(r"[^\w\-\u0600-\u06FF]+", "-", base, flags=re.UNICODE).strip("-")
    return base or "book"

def render_cover(pdf_path: Path, out_path: Path, zoom: float = 2.0) -> None:
    doc = fitz.open(pdf_path)
    try:
        page = doc.load_page(0)
        mat = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix=mat, alpha=False)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        pix.save(out_path.as_posix(), output="jpg")
    finally:
        doc.close()

def main() -> None:
    if not PDF_DIR.exists():
        print(f"PDF directory not found: {PDF_DIR}", file=sys.stderr)
        sys.exit(1)

    pdfs = sorted([p for p in PDF_DIR.glob("*.pdf")])
    if not pdfs:
        print(f"No PDFs found in {PDF_DIR}", file=sys.stderr)
        sys.exit(1)

    imports_pdf = []
    imports_cover = []
    entries = []

    for idx, pdf in enumerate(pdfs):
        slug = slugify(pdf.name)
        title = ARABIC_TITLES[idx] if idx < len(ARABIC_TITLES) else slug
        cover_name = f"{slug}.jpg"
        cover_path = COVERS_DIR / cover_name

        print(f"Rendering cover: {pdf.name} -> {cover_name}")
        render_cover(pdf, cover_path)

        pdf_var = f"pdf_{idx}"
        cover_var = f"cover_{idx}"
        # paths relative to src/data/books.js
        rel_pdf = f"../assets/pdfs/{pdf.name}"
        rel_cover = f"../assets/covers/{cover_name}"

        imports_pdf.append(f"import {pdf_var} from '{rel_pdf}';")
        imports_cover.append(f"import {cover_var} from '{rel_cover}';")

        entry = {
            "id": slug,
            "title": title,
            "category": "الكتب",
            "tags": [],
            "pdfVar": pdf_var,
            "coverVar": cover_var,
            "seriesId": "machine-series",
            "seriesIndex": idx + 1,
            "primaryCategoryId": "series",
            "categoryIds": ["series"],
        }
        entries.append(entry)

    # Write JS file
    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    with OUT_JS.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/generate_books.py\n")
        for line in imports_pdf + imports_cover:
            f.write(line + "\n")
        # Series and categories
        f.write("\nexport const SERIES = [\n")
        f.write("  { id: 'machine-series', title: 'سلسلة \"الآلة التي...\" | Arabic GPT Machine Series', slug: 'machine-series', categoryTitle: 'سلسلة \"الآلة التي...\" | Arabic GPT Machine Series', order: 1, accent: 'from-lime-400 to-emerald-500' }\n")
        f.write("]\n")
        f.write("\nexport const CATEGORIES = [\n")
        f.write("  { id: 'series', title: 'سلاسل الكتب', order: 1 }\n")
        f.write("]\n")

        # Books
        f.write("\nexport const BOOKS = [\n")
        for i, e in enumerate(entries):
            comma = "," if i < len(entries) - 1 else ""
            f.write(
                (
                    "  { id: '%(id)s', title: '%(title)s', slug: '%(id)s', category: '%(category)s', tags: [], "
                    "seriesId: '%(seriesId)s', seriesIndex: %(seriesIndex)d, primaryCategoryId: '%(primaryCategoryId)s', categoryIds: ['series'], "
                    "pdfUrl: %(pdfVar)s, downloadUrl: %(pdfVar)s, coverUrl: %(coverVar)s, viewUrl: %(pdfVar)s }%(comma)s\n"
                )
                % {**e, "comma": comma}
            )
        f.write(
            "]\n\n// Exports: SERIES, CATEGORIES, BOOKS\n"
        )

    print(f"Wrote {OUT_JS}")

if __name__ == "__main__":
    main()
