name: Deploy to GitHub Pages (Vite) [Node 20]

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Resolve base path
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          OWNER=${{ github.repository_owner }}
          if [ "$REPO_NAME" = "$OWNER.github.io" ]; then
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            echo "BASE_PATH=/$REPO_NAME/" >> $GITHUB_ENV
          fi

      - name: Build
        run: npm run build -- --base=${{ env.BASE_PATH }}

      - name: Print npm debug logs on failure
        if: failure()
        run: |
          echo "Scanning for npm debug logs..."
          LOG_DIR="$HOME/.npm/_logs"
          if [ -d "$LOG_DIR" ]; then
            echo "Found logs in $LOG_DIR";
            ls -lah "$LOG_DIR" || true
            for f in "$LOG_DIR"/*-debug-0.log; do
              [ -e "$f" ] || continue
              echo "----- $f -----"
              cat "$f" || true
            done
          fi
          echo "Checking workspace for *debug-0.log files..."
          find . -maxdepth 3 -type f -name "*debug-0.log" -print -exec sh -c 'echo "----- {} -----"; cat "{}"' \; || true

      - name: Upload npm logs artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: |
            ~/.npm/_logs/*
            **/*debug-0.log

      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

